-- Migration: Create currencies table
-- Author: Open Finance Development Team
-- Date: 2026-02-01
-- Version: V10
-- Description: Creates the currencies table for storing supported currencies with ISO 4217 codes
--              Requirement REQ-6.2: Multi-Currency Support

-- Create currencies table
CREATE TABLE currencies (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        VARCHAR(10) NOT NULL UNIQUE,      -- ISO 4217 currency code or common ticker (USD, BTC, USDT, etc.)
    name        VARCHAR(100) NOT NULL,            -- Full currency name (e.g., "US Dollar")
    symbol      VARCHAR(10) NOT NULL,             -- Currency symbol (e.g., "$", "€", "£")
    is_active   INTEGER NOT NULL DEFAULT 1,       -- Boolean: 1 = active, 0 = inactive
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Unique constraint on currency code
    CONSTRAINT uk_currency_code UNIQUE (code),
    
    -- Check constraint: code must be exactly 3 uppercase letters
    CONSTRAINT chk_currency_code_format
        CHECK (LENGTH(code) >= 3 AND LENGTH(code) <= 10 AND code = UPPER(code) AND code NOT GLOB '*[^A-Z]*')
);

-- Create index on active status for fast filtering
CREATE INDEX idx_currency_active ON currencies(is_active);

-- Migration: Seed full ISO 4217 currency list
-- Generated from java.util.Currency (Locale.ENGLISH)

INSERT INTO currencies (code, name, symbol, is_active) VALUES
    ('ADP', 'Andorran Peseta', 'ADP', 1),
    ('AED', 'United Arab Emirates Dirham', 'AED', 1),
    ('AFA', 'Afghan Afghani (1927–2002)', 'AFA', 1),
    ('AFN', 'Afghan Afghani', 'AFN', 1),
    ('ALL', 'Albanian Lek', 'ALL', 1),
    ('AMD', 'Armenian Dram', 'AMD', 1),
    ('ANG', 'Netherlands Antillean Guilder', 'ANG', 1),
    ('AOA', 'Angolan Kwanza', 'AOA', 1),
    ('ARS', 'Argentine Peso', 'ARS', 1),
    ('ATS', 'Austrian Schilling', 'ATS', 1),
    ('AUD', 'Australian Dollar', 'A$', 1),
    ('AWG', 'Aruban Florin', 'AWG', 1),
    ('AYM', 'AYM', 'AYM', 1),
    ('AZM', 'Azerbaijani Manat (1993–2006)', 'AZM', 1),
    ('AZN', 'Azerbaijani Manat', 'AZN', 1),
    ('BAM', 'Bosnia-Herzegovina Convertible Mark', 'BAM', 1),
    ('BBD', 'Barbadian Dollar', 'BBD', 1),
    ('BDT', 'Bangladeshi Taka', 'BDT', 1),
    ('BEF', 'Belgian Franc', 'BEF', 1),
    ('BGL', 'Bulgarian Hard Lev', 'BGL', 1),
    ('BGN', 'Bulgarian Lev', 'BGN', 1),
    ('BHD', 'Bahraini Dinar', 'BHD', 1),
    ('BIF', 'Burundian Franc', 'BIF', 1),
    ('BMD', 'Bermudan Dollar', 'BMD', 1),
    ('BND', 'Brunei Dollar', 'BND', 1),
    ('BOB', 'Bolivian Boliviano', 'BOB', 1),
    ('BOV', 'Bolivian Mvdol', 'BOV', 1),
    ('BRL', 'Brazilian Real', 'R$', 1),
    ('BSD', 'Bahamian Dollar', 'BSD', 1),
    ('BTN', 'Bhutanese Ngultrum', 'BTN', 1),
    ('BWP', 'Botswanan Pula', 'BWP', 1),
    ('BYB', 'Belarusian Ruble (1994–1999)', 'BYB', 1),
    ('BYN', 'Belarusian Ruble', 'BYN', 1),
    ('BYR', 'Belarusian Ruble (2000–2016)', 'BYR', 1),
    ('BZD', 'Belize Dollar', 'BZD', 1),
    ('CAD', 'Canadian Dollar', 'CA$', 1),
    ('CDF', 'Congolese Franc', 'CDF', 1),
    ('CHE', 'WIR Euro', 'CHE', 1),
    ('CHF', 'Swiss Franc', 'CHF', 1),
    ('CHW', 'WIR Franc', 'CHW', 1),
    ('CLF', 'Chilean Unit of Account (UF)', 'CLF', 1),
    ('CLP', 'Chilean Peso', 'CLP', 1),
    ('CNY', 'Chinese Yuan', 'CN¥', 1),
    ('COP', 'Colombian Peso', 'COP', 1),
    ('COU', 'Colombian Real Value Unit', 'COU', 1),
    ('CRC', 'Costa Rican Colón', 'CRC', 1),
    ('CSD', 'Serbian Dinar (2002–2006)', 'CSD', 1),
    ('CUC', 'Cuban Convertible Peso', 'CUC', 1),
    ('CUP', 'Cuban Peso', 'CUP', 1),
    ('CVE', 'Cape Verdean Escudo', 'CVE', 1),
    ('CYP', 'Cypriot Pound', 'CYP', 1),
    ('CZK', 'Czech Koruna', 'CZK', 1),
    ('DEM', 'German Mark', 'DEM', 1),
    ('DJF', 'Djiboutian Franc', 'DJF', 1),
    ('DKK', 'Danish Krone', 'DKK', 1),
    ('DOP', 'Dominican Peso', 'DOP', 1),
    ('DZD', 'Algerian Dinar', 'DZD', 1),
    ('EEK', 'Estonian Kroon', 'EEK', 1),
    ('EGP', 'Egyptian Pound', 'EGP', 1),
    ('ERN', 'Eritrean Nakfa', 'ERN', 1),
    ('ESP', 'Spanish Peseta', 'ESP', 1),
    ('ETB', 'Ethiopian Birr', 'ETB', 1),
    ('EUR', 'Euro', '€', 1),
    ('FIM', 'Finnish Markka', 'FIM', 1),
    ('FJD', 'Fijian Dollar', 'FJD', 1),
    ('FKP', 'Falkland Islands Pound', 'FKP', 1),
    ('FRF', 'French Franc', 'FRF', 1),
    ('GBP', 'British Pound', '£', 1),
    ('GEL', 'Georgian Lari', 'GEL', 1),
    ('GHC', 'Ghanaian Cedi (1979–2007)', 'GHC', 1),
    ('GHS', 'Ghanaian Cedi', 'GHS', 1),
    ('GIP', 'Gibraltar Pound', 'GIP', 1),
    ('GMD', 'Gambian Dalasi', 'GMD', 1),
    ('GNF', 'Guinean Franc', 'GNF', 1),
    ('GRD', 'Greek Drachma', 'GRD', 1),
    ('GTQ', 'Guatemalan Quetzal', 'GTQ', 1),
    ('GWP', 'Guinea-Bissau Peso', 'GWP', 1),
    ('GYD', 'Guyanaese Dollar', 'GYD', 1),
    ('HKD', 'Hong Kong Dollar', 'HK$', 1),
    ('HNL', 'Honduran Lempira', 'HNL', 1),
    ('HRK', 'Croatian Kuna', 'HRK', 1),
    ('HTG', 'Haitian Gourde', 'HTG', 1),
    ('HUF', 'Hungarian Forint', 'HUF', 1),
    ('IDR', 'Indonesian Rupiah', 'IDR', 1),
    ('IEP', 'Irish Pound', 'IEP', 1),
    ('ILS', 'Israeli New Shekel', '₪', 1),
    ('INR', 'Indian Rupee', '₹', 1),
    ('IQD', 'Iraqi Dinar', 'IQD', 1),
    ('IRR', 'Iranian Rial', 'IRR', 1),
    ('ISK', 'Icelandic Króna', 'ISK', 1),
    ('ITL', 'Italian Lira', 'ITL', 1),
    ('JMD', 'Jamaican Dollar', 'JMD', 1),
    ('JOD', 'Jordanian Dinar', 'JOD', 1),
    ('JPY', 'Japanese Yen', '¥', 1),
    ('KES', 'Kenyan Shilling', 'KES', 1),
    ('KGS', 'Kyrgystani Som', 'KGS', 1),
    ('KHR', 'Cambodian Riel', 'KHR', 1),
    ('KMF', 'Comorian Franc', 'KMF', 1),
    ('KPW', 'North Korean Won', 'KPW', 1),
    ('KRW', 'South Korean Won', '₩', 1),
    ('KWD', 'Kuwaiti Dinar', 'KWD', 1),
    ('KYD', 'Cayman Islands Dollar', 'KYD', 1),
    ('KZT', 'Kazakhstani Tenge', 'KZT', 1),
    ('LAK', 'Laotian Kip', 'LAK', 1),
    ('LBP', 'Lebanese Pound', 'LBP', 1),
    ('LKR', 'Sri Lankan Rupee', 'LKR', 1),
    ('LRD', 'Liberian Dollar', 'LRD', 1),
    ('LSL', 'Lesotho Loti', 'LSL', 1),
    ('LTL', 'Lithuanian Litas', 'LTL', 1),
    ('LUF', 'Luxembourgian Franc', 'LUF', 1),
    ('LVL', 'Latvian Lats', 'LVL', 1),
    ('LYD', 'Libyan Dinar', 'LYD', 1),
    ('MAD', 'Moroccan Dirham', 'MAD', 1),
    ('MDL', 'Moldovan Leu', 'MDL', 1),
    ('MGA', 'Malagasy Ariary', 'MGA', 1),
    ('MGF', 'Malagasy Franc', 'MGF', 1),
    ('MKD', 'Macedonian Denar', 'MKD', 1),
    ('MMK', 'Myanmar Kyat', 'MMK', 1),
    ('MNT', 'Mongolian Tugrik', 'MNT', 1),
    ('MOP', 'Macanese Pataca', 'MOP', 1),
    ('MRO', 'Mauritanian Ouguiya (1973–2017)', 'MRO', 1),
    ('MRU', 'Mauritanian Ouguiya', 'MRU', 1),
    ('MTL', 'Maltese Lira', 'MTL', 1),
    ('MUR', 'Mauritian Rupee', 'MUR', 1),
    ('MVR', 'Maldivian Rufiyaa', 'MVR', 1),
    ('MWK', 'Malawian Kwacha', 'MWK', 1),
    ('MXN', 'Mexican Peso', 'MX$', 1),
    ('MXV', 'Mexican Investment Unit', 'MXV', 1),
    ('MYR', 'Malaysian Ringgit', 'MYR', 1),
    ('MZM', 'Mozambican Metical (1980–2006)', 'MZM', 1),
    ('MZN', 'Mozambican Metical', 'MZN', 1),
    ('NAD', 'Namibian Dollar', 'NAD', 1),
    ('NGN', 'Nigerian Naira', 'NGN', 1),
    ('NIO', 'Nicaraguan Córdoba', 'NIO', 1),
    ('NLG', 'Dutch Guilder', 'NLG', 1),
    ('NOK', 'Norwegian Krone', 'NOK', 1),
    ('NPR', 'Nepalese Rupee', 'NPR', 1),
    ('NZD', 'New Zealand Dollar', 'NZ$', 1),
    ('OMR', 'Omani Rial', 'OMR', 1),
    ('PAB', 'Panamanian Balboa', 'PAB', 1),
    ('PEN', 'Peruvian Sol', 'PEN', 1),
    ('PGK', 'Papua New Guinean Kina', 'PGK', 1),
    ('PHP', 'Philippine Peso', '₱', 1),
    ('PKR', 'Pakistani Rupee', 'PKR', 1),
    ('PLN', 'Polish Zloty', 'PLN', 1),
    ('PTE', 'Portuguese Escudo', 'PTE', 1),
    ('PYG', 'Paraguayan Guarani', 'PYG', 1),
    ('QAR', 'Qatari Riyal', 'QAR', 1),
    ('ROL', 'Romanian Leu (1952–2006)', 'ROL', 1),
    ('RON', 'Romanian Leu', 'RON', 1),
    ('RSD', 'Serbian Dinar', 'RSD', 1),
    ('RUB', 'Russian Ruble', 'RUB', 1),
    ('RUR', 'Russian Ruble (1991–1998)', 'RUR', 1),
    ('RWF', 'Rwandan Franc', 'RWF', 1),
    ('SAR', 'Saudi Riyal', 'SAR', 1),
    ('SBD', 'Solomon Islands Dollar', 'SBD', 1),
    ('SCR', 'Seychellois Rupee', 'SCR', 1),
    ('SDD', 'Sudanese Dinar (1992–2007)', 'SDD', 1),
    ('SDG', 'Sudanese Pound', 'SDG', 1),
    ('SEK', 'Swedish Krona', 'SEK', 1),
    ('SGD', 'Singapore Dollar', 'SGD', 1),
    ('SHP', 'St. Helena Pound', 'SHP', 1),
    ('SIT', 'Slovenian Tolar', 'SIT', 1),
    ('SKK', 'Slovak Koruna', 'SKK', 1),
    ('SLE', 'Sierra Leonean Leone', 'SLE', 1),
    ('SLL', 'Sierra Leonean Leone (1964—2022)', 'SLL', 1),
    ('SOS', 'Somali Shilling', 'SOS', 1),
    ('SRD', 'Surinamese Dollar', 'SRD', 1),
    ('SRG', 'Surinamese Guilder', 'SRG', 1),
    ('SSP', 'South Sudanese Pound', 'SSP', 1),
    ('STD', 'São Tomé & Príncipe Dobra (1977–2017)', 'STD', 1),
    ('STN', 'São Tomé & Príncipe Dobra', 'STN', 1),
    ('SVC', 'Salvadoran Colón', 'SVC', 1),
    ('SYP', 'Syrian Pound', 'SYP', 1),
    ('SZL', 'Swazi Lilangeni', 'SZL', 1),
    ('THB', 'Thai Baht', 'THB', 1),
    ('TJS', 'Tajikistani Somoni', 'TJS', 1),
    ('TMM', 'Turkmenistani Manat (1993–2009)', 'TMM', 1),
    ('TMT', 'Turkmenistani Manat', 'TMT', 1),
    ('TND', 'Tunisian Dinar', 'TND', 1),
    ('TOP', 'Tongan Paʻanga', 'TOP', 1),
    ('TPE', 'Timorese Escudo', 'TPE', 1),
    ('TRL', 'Turkish Lira (1922–2005)', 'TRL', 1),
    ('TRY', 'Turkish Lira', 'TRY', 1),
    ('TTD', 'Trinidad & Tobago Dollar', 'TTD', 1),
    ('TWD', 'New Taiwan Dollar', 'NT$', 1),
    ('TZS', 'Tanzanian Shilling', 'TZS', 1),
    ('UAH', 'Ukrainian Hryvnia', 'UAH', 1),
    ('UGX', 'Ugandan Shilling', 'UGX', 1),
    ('USD', 'US Dollar', '$', 1),
    ('USN', 'US Dollar (Next day)', 'USN', 1),
    ('USS', 'US Dollar (Same day)', 'USS', 1),
    ('UYI', 'Uruguayan Peso (Indexed Units)', 'UYI', 1),
    ('UYU', 'Uruguayan Peso', 'UYU', 1),
    ('UZS', 'Uzbekistani Som', 'UZS', 1),
    ('VEB', 'Venezuelan Bolívar (1871–2008)', 'VEB', 1),
    ('VED', 'Bolívar Soberano', 'VED', 1),
    ('VEF', 'Venezuelan Bolívar (2008–2018)', 'VEF', 1),
    ('VES', 'Venezuelan Bolívar', 'VES', 1),
    ('VND', 'Vietnamese Dong', '₫', 1),
    ('VUV', 'Vanuatu Vatu', 'VUV', 1),
    ('WST', 'Samoan Tala', 'WST', 1),
    ('XAD', 'Arab Accounting Dinar', 'XAD', 1),
    ('XAF', 'Central African CFA Franc', 'FCFA', 1),
    ('XAG', 'Silver', 'XAG', 1),
    ('XAU', 'Gold', 'XAU', 1),
    ('XBA', 'European Composite Unit', 'XBA', 1),
    ('XBB', 'European Monetary Unit', 'XBB', 1),
    ('XBC', 'European Unit of Account (XBC)', 'XBC', 1),
    ('XBD', 'European Unit of Account (XBD)', 'XBD', 1),
    ('XCD', 'East Caribbean Dollar', 'EC$', 1),
    ('XCG', 'Caribbean Guilder', 'XCG', 1),
    ('XDR', 'Special Drawing Rights', 'XDR', 1),
    ('XFO', 'French Gold Franc', 'XFO', 1),
    ('XFU', 'French UIC-Franc', 'XFU', 1),
    ('XOF', 'West African CFA Franc', 'F CFA', 1),
    ('XPD', 'Palladium', 'XPD', 1),
    ('XPF', 'CFP Franc', 'CFPF', 1),
    ('XPT', 'Platinum', 'XPT', 1),
    ('XSU', 'Sucre', 'XSU', 1),
    ('XTS', 'Testing Currency Code', 'XTS', 1),
    ('XUA', 'ADB Unit of Account', 'XUA', 1),
    ('XXX', 'Unknown Currency', '¤', 1),
    ('YER', 'Yemeni Rial', 'YER', 1),
    ('YUM', 'Yugoslavian New Dinar (1994–2002)', 'YUM', 1),
    ('ZAR', 'South African Rand', 'ZAR', 1),
    ('ZMK', 'Zambian Kwacha (1968–2012)', 'ZMK', 1),
    ('ZMW', 'Zambian Kwacha', 'ZMW', 1),
    ('ZWD', 'Zimbabwean Dollar (1980–2008)', 'ZWD', 1),
    ('ZWG', 'Zimbabwe Gold', 'ZWG', 1),
    ('ZWL', 'Zimbabwean Dollar (2009)', 'ZWL', 1),
    ('ZWN', 'ZWN', 'ZWN', 1),
    ('ZWR', 'Zimbabwean Dollar (2008)', 'ZWR', 1);

-- Cryptocurrencies (common digital assets)
INSERT INTO currencies (code, name, symbol, is_active) VALUES
    ('BTC', 'Bitcoin', '₿', 1),
    ('ETH', 'Ethereum', 'Ξ', 1),
    ('BNB', 'Binance Coin', 'BNB', 1),
    ('XRP', 'Ripple', 'XRP', 1),
    ('ADA', 'Cardano', 'ADA', 1),
    ('SOL', 'Solana', 'SOL', 1),
    ('DOT', 'Polkadot', 'DOT', 1),
    ('DOGE', 'Dogecoin', 'Ð', 1),
    ('USDT', 'Tether', 'USDT', 1),
    ('USDC', 'USD Coin', 'USDC', 1);

-- Comments for documentation
-- Note: SQLite doesn't support column comments directly, but this serves as documentation
-- 
-- Currency codes follow ISO 4217 standard for fiat currencies (3-letter codes)
-- Cryptocurrencies use common ticker symbols (BTC, ETH, etc.)
-- 
-- is_active field:
--   1 = Active currency (available for selection in UI)
--   0 = Inactive currency (deprecated, kept for historical data integrity)
--
-- Usage notes:
--   - When adding new currencies, ensure code is unique and follows 3-letter format
--   - Symbol can be multi-character for currencies without single-character symbols
--   - Use is_active=0 to deprecate currencies without breaking historical records

-- Migration validation queries (commented out - for reference only)
-- SELECT COUNT(*) FROM currencies WHERE is_active = 1;  -- Should be 40 (30 fiat + 10 crypto)
-- SELECT * FROM currencies WHERE code IN ('USD', 'EUR', 'GBP', 'BTC', 'ETH');  -- Verify key currencies
-- SELECT COUNT(DISTINCT code) FROM currencies;  -- Should equal total row count (uniqueness check)
